str=input("Enter the string =>")
print("string is ",str)
print("length of string",len(str))
print("string slice str [2:5] ",str[2:5]  )
print("string slice str [:6] ",str[:6]  )
print("string slice str [3:] ",str[3:]  )
print("string slice str [ : : 2] ",str[ : : 2]  )
print("string slice str [3:7:2] ",str[3:7:2]  )
print("string slice str [-1:-5:-1] ",str[-1:-5:-1]  )
