from tkinter import *
root=Tk()
root.geometry("300x200")
w=Label(root,text="my Checkbox",font="50")
w.pack()
checkbutton1=IntVar()
checkbutton2=IntVar()
checkbutton3=IntVar()
btn1=Checkbutton(root,text="my Tutorial",variable=checkbutton1,onvalue=1,offvalue=0,height=2,width=10)
btn2=Checkbutton(root,text="Student",variable=checkbutton2,onvalue=1,offvalue=0,height=2,width=10)
btn3=Checkbutton(root,text="cources",variable=checkbutton3,onvalue=1,offvalue=0,height=2,width=10)
btn1.pack()
btn2.pack()
btn3.pack()
root.mainloop()